# fly.toml app configuration file for Go WebSocket server with React frontend
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'redisconnect-go'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '5000'
  REACT_APP_WEBSOCKET_URL="http://localhost:5000"
  REACT_APP_SIGNALING_URL="https://gosignaling-app.fly.dev/connect"
  REACT_APP_HIGMA_ICON_PATH="/map/channels4_profile.jpg"
  REACT_APP_HASURA_ENDPOINT="https://apt-panther-30.hasura.app/v1/graphql"
  REACT_APP_HASURA_ADMIN_SECRET="GLwNuQEwAPIY1hFgp43i5XsSOGTvcu69y2GA5sR1ES51DAOIf5evfCrWfT4KxfPs"
  REACT_APP_GRAPH_HOPPER_API_KEY="e8c7999a-f5a7-4f79-b7bc-dd1b5fd61ef8"
  REACT_APP_GRAPH_HOPPER_BASE_URL="https://graphhopper.com/api/1"

  REDIS_HOST="redis-16155.c270.us-east-1-3.ec2.redns.redis-cloud.com"
  REDIS_PORT="16155"
  REDIS_USERNAME="default"
  REDIS_PASSWORD="wDpC7hY1CkdDOkjP6xP09UtzlCp5SL5Q"
  HIGMA_API_URL="https://tthogho1-higmachat.hf.space/api/chat"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  # Enable WebSocket connections
  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
